### ISSUE TITLE
Inline icons in links

### ISSUE THREAD

**Issue by warpech** [Starcounter/underwear.css#20]
For BlendingEditor, I needed to come up with a way to do inline icons in links that looks like:

> ![image](https://user-images.githubusercontent.com/566463/35579914-1f4af8d4-05e8-11e8-8ea9-91cd96abd7a2.png)

My proposal is to do this in your HTML code:

```html
<a href="/BlendingEditor/surface/{{model.Surface.Key}}/preview" class="website-general-preview__link" target="_blank">
    Open in new window
    <svg data-underwear="inline icon" aria-hidden="true" viewBox="0 0 18 18" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <use xlink:href="/BlendingEditor/images/external-link.svg#icon""></use>
    </svg>
</a>
```

That assumes that the following rule is in Underwear.css:

```css
svg[data-underwear="inline icon"] {
    display: inline-block;
    fill: currentColor;
    height: 1em;
    vertical-align: text-bottom;
}
```

The above rule contradicts the assumption of Underwear.css. But on the other hand it cannot be applied in Shadow DOM. This is why, in my opininion, it belongs in `Underwear.css` or something that I would call `UnderwearExtensions.css`.

@Starcounter/webplatformteam WDYT?
