### ISSUE TITLE
Cleanup the CSS property names

### ISSUE THREAD

**Issue by warpech** [Starcounter/underwear.css#32]
Currently there are the following property names in use:

```css
:root {
  --dark: #141d26;
  --inky: #1b2936;
  --livid: #8696a5;
  --transparent-black: #00000033;
  --mouse: #e7ecf0;
  --blue-dark: #1a587f;
  --blue: #0084b4;
  --platinum: #e7e7e7;
  --white: #ffffff;
  --white-smoke: #f9f9f9;
  --light: #f6f6f6;
  --yellow: #ffdb25;
  --red: #df4534;
  --green: #3fa13f;
  --darkgray: #868e96;
  --light-gray: #e1e1e1;
  --bluish-gray: #606c76;

  --default-font-size: 14px;
  --default-body-color: var(--dark);
  --blockquote-border-color: var(--livid);
  --shadow-color: var(--transparent-black);
  --editables-background-color: var(--light);
  --button-background-color: var(--while);
  --disabled-background-color: var(--light);
  --button-hover-background-color: var(--mouse);
  --button-text-color: var(--dark);
  --disabled-element-text-color: var(--darkgray);
  --table-border-color: var(--light-gray);
  --code-block-bg-color: var(--light);
  --code-block-color: var(--red);
  --code-block-border-color: var(--blue);
  --anchor-color: var(--blue);
  --table-border-color: var(--light-gray);

  --font-family-sans-serif: 'Roboto', 'Segoe UI', 'Helvetica Neue', Arial,
    sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
  --font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas,
'Liberation Mono', 'Courier New', monospace;
}
```

I have the following comments:

1. use the singular form consistently (change `editables-background-color` to `editable-background-color`)
2. the word `element` is redundant (change `disabled-element-text-color` to `disabled-text-color`)
3. the word `block` is redundant (change `code-block` to `code`)
4. use the word `background` consistently (never use `bg`, use `background`)
5. use the hyphenation consistently (change `darkgray` to `dark-gray`)
6. use the word `dark` consistently (change `blue-dark` to `dark-blue`)
7. our gray pallette has ridiculously inconsistent naming: `transparent-black`, `platinum`, `white`, `white-smoke`, `light`, `light-gray`. Compare it with [Bootstrap](https://github.com/twbs/bootstrap/blob/f81f419b22949d2bf0f4d346891be44724109135/scss/_variables.scss#L12-L22), [Bulma](https://github.com/jgthms/bulma/blob/master/sass/utilities/initial-variables.sass#L3-L15) or [MCW](https://github.com/material-components/material-components-web/blob/9bb3be544b5b2390e7a7ab31cf40047028494e20/packages/mdc-theme/_color-palette.scss#L270-L279). I would prefer: `white`, `gray-1`, `gray-2`, `gray-3`, `gray-4`, `black`, `black-transparent`.
