### ISSUE TITLE
idea: Store colors in RGB or HSL numbers, so we could compose opacity

### ISSUE THREAD

**Issue by tomalec** [Starcounter/underwear.css#44]
With 
```
:root {
  --color: 240, 240, 240;
  --disabled-opacity: 0.5;
}
```
We could do
```css
something{
  background-color: rgb(var(--color));
}
something[disabled]{
  background-color: rgba(var(--color), var(disabled-opacity));
}
```
without fading out the content with `opacity: 0.5`.

The downside of that is:
- harder job for polyfills,
- harder job for browser - performance?
- no IDE highlights like https://atom.io/packages/pigments

//cc @alshakero @warpech
